import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className="dark" lang="en">
			<body className="dark:bg-gray-800">{children}</body>
		</html>
	);
}
